<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class Webiny\Component\Rest\Tests\Mocks\MockApiClassNew
 * @rest.version v1.1
 * @rest.aliasVersion latest
 * @rest.url |url|
 * @rest.buildDate Wed, 27. Aug, 2014 00:09:51
 */

$a = include "/var/www/projects/webiny/Vendors/Webiny/Component/Rest/Tests/TempCache/ExampleApi/Webiny_Component_Rest_Tests_Mocks_MockApiClass/v1.1.php";


return $a;