<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class Webiny\Component\Rest\Tests\Mocks\MockApiClass
 * @rest.version v1.0
 * @rest.buildDate Wed, 27. Aug, 2014 00:09:51
 */

$a = array(
    'class'             => 'Webiny\\Component\\Rest\\Tests\\Mocks\\MockApiClass',
    'cacheKeyInterface' => false,
    'accessInterface'   => false,
    'version'           => '1.0',
    'post'              => array(
        'some-method/([\\w-]+)/([\\w-]+)/([\\d]+)/' => array(
            'default'     => '',
            'role'        => 'SECRET',
            'method'      => 'someMethod',
            'urlPattern'  => 'some-method',
            'cache'       => array(
                'ttl' => '3600',
            ),
            'header'      => array(
                'cache'  => array(
                    'expires' => '3600',
                ),
                'status' => array(
                    'success'      => '201',
                    'error'        => '403',
                    'errorMessage' => 'No Author for specified id.',
                ),
            ),
            'rateControl' => array(
                'ignore' => '',
            ),
            'params'      => array(
                'param1' => array(
                    'required' => true,
                    'type'     => 'string',
                    'default'  => null,
                ),
                'param2' => array(
                    'required' => false,
                    'type'     => 'string',
                    'default'  => 'default',
                ),
                'param3' => array(
                    'required' => false,
                    'type'     => 'integer',
                    'default'  => 22,
                ),
            ),
        ),
    ),
    'get'               => array(
        'simple-method/' => array(
            'default'     => false,
            'role'        => false,
            'method'      => 'simpleMethod',
            'urlPattern'  => 'simple-method',
            'cache'       => array(
                'ttl' => 0,
            ),
            'header'      => array(
                'cache'  => array(
                    'expires' => 0,
                ),
                'status' => array(
                    'success'      => 200,
                    'error'        => 404,
                    'errorMessage' => '',
                ),
            ),
            'rateControl' => array(),
            'params'      => array(),
        ),
    ),
);


return $a;