<?php

/**
 * This is an auto generated file by Webiny Rest component.
 * Please do not edit this file because the changes might break your REST Api.
 *
 * @rest.class |class|
 * @rest.version |version|
 * @rest.aliasVersion |aliasVersion|
 * @rest.url |url|
 * @rest.buildDate |buildDate|
 */

$a = |export|;


return $a;