##################################
# Entity - example configuration #
##################################

# This is an example configuration of Entity component
# The only thing there is to configure is the database service Entity component will use for storing data
# Entity depends on Mongo component so here we specify Mongo service name, in our case Webiny (default Mongo service name)
#
# You can also override default attribute classes by specifying a map of attribute name and a new class to use.
Entity:
    Database: Webiny
    Attributes:
        char: \Webiny\Component\Entity\Attribute\CharAttribute